/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package generadordni;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author fernandos
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();

        disenoGUI();
        
        setLocationRelativeTo(null);
        
        JRadioButton[] rdbs={rdbDNI, rdbNIE, rdbCIF};
        agruparRadioButton(rdbs);
        
        bordeConTitulo(panelTipoDocumento, "Tipo de documento");
        bordeConTitulo(panelCantidad, "Cantidad");
        bordeConTitulo(panelResultado, "Resultados");
        
        JLabelLink lbl=new JLabelLink();
        
        lbl.setSize(303, 37);
        
        lbl.setLink("http://www.discoduroderoer.es");
        lbl.setText("Aplicación creada por Fernando Ureña Gómez, creador de <b>Disco Duro de Roer</b>");
        lbl.setTextLink("Disco Duro de Roer");
        lbl.setBounds(label.getX(), label.getY(), label.getWidth(), label.getHeight());

        this.add(lbl);
        
    }
    
    public static void disenoGUI(){
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e){
            System.out.println("Error setting Java LAF: "+e);
        }
    }
    
    public static void agruparRadioButton(JRadioButton[] radios){
        ButtonGroup grupo=new ButtonGroup();
        
        for(int i=0;i<radios.length;i++){
            grupo.add(radios[i]);
        }
    }
    
    public static void bordeConTitulo(JPanel panel, String titulo){
        panel.setBorder(BorderFactory.createTitledBorder(titulo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGenerar = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        panelTipoDocumento = new javax.swing.JPanel();
        rdbDNI = new javax.swing.JRadioButton();
        rdbNIE = new javax.swing.JRadioButton();
        rdbCIF = new javax.swing.JRadioButton();
        panelCantidad = new javax.swing.JPanel();
        spnNum = new javax.swing.JSpinner();
        panelResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDNI = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador DNI, NIE y CIF");
        setResizable(false);

        botonGenerar.setText("Generar");
        botonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarActionPerformed(evt);
            }
        });

        rdbDNI.setSelected(true);
        rdbDNI.setText("DNI");

        rdbNIE.setText("NIE");
        rdbNIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNIEActionPerformed(evt);
            }
        });

        rdbCIF.setText("CIF");

        javax.swing.GroupLayout panelTipoDocumentoLayout = new javax.swing.GroupLayout(panelTipoDocumento);
        panelTipoDocumento.setLayout(panelTipoDocumentoLayout);
        panelTipoDocumentoLayout.setHorizontalGroup(
            panelTipoDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoDocumentoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelTipoDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbCIF)
                    .addComponent(rdbNIE)
                    .addComponent(rdbDNI, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelTipoDocumentoLayout.setVerticalGroup(
            panelTipoDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipoDocumentoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(rdbDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbNIE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCIF)
                .addContainerGap())
        );

        spnNum.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnNum.setEditor(new javax.swing.JSpinner.NumberEditor(spnNum, ""));
        spnNum.setRequestFocusEnabled(false);
        spnNum.setValue(1);
        spnNum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spnNumPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelCantidadLayout = new javax.swing.GroupLayout(panelCantidad);
        panelCantidad.setLayout(panelCantidadLayout);
        panelCantidadLayout.setHorizontalGroup(
            panelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnNum, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCantidadLayout.setVerticalGroup(
            panelCantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantidadLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(spnNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        txtAreaDNI.setEditable(false);
        txtAreaDNI.setColumns(20);
        txtAreaDNI.setLineWrap(true);
        txtAreaDNI.setRows(5);
        txtAreaDNI.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaDNI);

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(panelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(botonGenerar)
                        .addGap(75, 75, 75)))
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        label.getAccessibleContext().setAccessibleName("<html><p align=\"center\">Aplicación creada por Fernando Ureña Gómez, creador de<a href=\"http://www.discoduroderoer.es\"> Disco Duro de Roer</a></p></html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarActionPerformed
       
        txtAreaDNI.setText("");
        
        if (rdbDNI.isSelected()){
            
            String[] dnis = DNI.generaDNIsAletorios((int)spnNum.getValue());
            
            for (int i=0;i<dnis.length;i++){
                
                txtAreaDNI.append(dnis[i]+"\n");
                
            }
            
        }else if(rdbNIE.isSelected()){
            
            String[] nies = DNI.generaNIEsAletorios((int)spnNum.getValue());
            
            for (int i=0;i<nies.length;i++){
                
                txtAreaDNI.append(nies[i]+"\n");
                
            }
            
        }else{
            
            String[] cifs = DNI.generaCIFsAletorios((int)spnNum.getValue());
            
             for (int i=0;i<cifs.length;i++){
                
                txtAreaDNI.append(cifs[i]+"\n");
                
            }
            
        }
        
        
    }//GEN-LAST:event_botonGenerarActionPerformed

    private void rdbNIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNIEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNIEActionPerformed

    private void spnNumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spnNumPropertyChange
        
    }//GEN-LAST:event_spnNumPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panelCantidad;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelTipoDocumento;
    private javax.swing.JRadioButton rdbCIF;
    private javax.swing.JRadioButton rdbDNI;
    private javax.swing.JRadioButton rdbNIE;
    private javax.swing.JSpinner spnNum;
    private javax.swing.JTextArea txtAreaDNI;
    // End of variables declaration//GEN-END:variables
}
